spring.application.name=studentinfo
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:9090/studentinfo
spring.datasource.username=studentinfo
spring.datasource.password=welcome

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update